### ISSUE TITLE
DNSの自動デプロイ

### ISSUE THREAD

**Issue by momeemt** [sohosai/infrastructure#1]
## 概要
sohosai.comのネームサーバはCloudflareにあるが、多くのレコード（おそらくSOS以外）は手動で追加されている。
terraformのcloudflare providerを使って、自動でデプロイされるようにしたい。

### 実現したい機能
- mainブランチが更新されると、terraformファイルに従ってレコードを設定する

- ~~mainブランチでは常にterafformのコードの品質を保ちたい~~
  - #9 でした
- ~~反映後には差分についてMattermostの特定のチャンネルに通知したい~~
  - こちらは別タスクで、Cloudflareに限らず全ての変更について通知したくて、それはApplyワークフローの結果を吸い上げて送信すれば十分っぽい
- ~~詳しくないので分からないが、事故が起きたときにすぐに復旧可能な仕組みを入れておきたい~~
  - こちらも別タスクで

### 補足
- 基本的には全てのレコードを移してください
  - https://github.com/sohosai/infra/issues/12 は現状の用途確認を行った後、/terraformから削除します
- ただし以下のレコードは除いてください
  - Mattermostで直接したレコード
  - sendgrid関連（CNAMEの e* と s*._domainkey）
  - SOSのAPIサーバのレコード
    - api.online
    - api.beta.online
    - api.nightly.online

**Comment by appare45** [comment]
@momeemt リソースの名前に命名規則はありますか？

当初は`name`をそのままリソース名にしてたのですがリソース名が重複するのですがどうするのが良いでしょうか

**Comment by momeemt** [comment]
@appare45 

特に設定していませんでした。おっしゃるようにユニークなidを入れるか、コンテンツに関連するその時点でユニークな情報を入れるのが良いと思います。
以下の箇条書きの内容について、昇順に試していただけるとありがたいです。

1. `name`をそのままリソース名にする（`sohosai_com`）
2. コンテンツに関連する情報を`name`の後にアンダーバーで区切って追記する（`sohosai_com_alt1`）
3. 関連するユニークな情報を付加できなければUUID v4（ハイフンなし、小文字）をアンダーバーで区切って追記する（`sohosai_com_907221c1d6124659a99d4636bef04834`）

uuidv4にしたのは私があまりユニークな値に詳しくないからで、より適した物があったら提案してそちらを使ってもらっても大丈夫です。

**Comment by momeemt** [comment]
あと、この内容については https://github.com/sohosai/terraform/tree/main/docs 以下に書いておいてもらえると助かります！:pray:
